//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onquanlyrapphim
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAPPHIM
    {
        public string MADON { get; set; }
        public string TENPHIM { get; set; }
        public string QUOCGIA { get; set; }
        public string THELOAI { get; set; }
        public Nullable<System.DateTime> NGAYCONGCHIEU { get; set; }
        public Nullable<int> DOTUOIQUYDINH { get; set; }
        public Nullable<decimal> PHUTHUGHE { get; set; }
        public Nullable<decimal> PHUTHUSUATDATBIET { get; set; }
        public Nullable<decimal> DOANHTHU { get; set; }
    }
}
