//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTTH24_11.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class nv
    {
        public string maphongvien { get; set; }
        public string hoten { get; set; }
        public Nullable<bool> gioitinh { get; set; }
        public string sodienthoai { get; set; }
        public Nullable<System.DateTime> ngayvaolam { get; set; }
        public Nullable<double> phucap { get; set; }
        public Nullable<int> sogiolamthem { get; set; }
    }
}
