//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTTH24_11.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class thucung
    {
        public string madon { get; set; }
        public string tenthucung { get; set; }
        public string chungloai { get; set; }
        public Nullable<int> cannang { get; set; }
        public Nullable<System.DateTime> ngaynhan { get; set; }
        public string tinhtrang { get; set; }
        public Nullable<double> chiphithuocdieutri { get; set; }
        public Nullable<int> songay { get; set; }
    }
}
